# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.APELL = QtWidgets.QLabel(self.centralwidget)
        self.APELL.setGeometry(QtCore.QRect(130, 170, 61, 16))
        self.APELL.setObjectName("APELL")
        self.XECL = QtWidgets.QLabel(self.centralwidget)
        self.XECL.setGeometry(QtCore.QRect(260, 50, 251, 31))
        self.XECL.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"font: 75 14pt \"Tahoma\";\n"
"")
        self.XECL.setObjectName("XECL")
        self.NOMBRE = QtWidgets.QLabel(self.centralwidget)
        self.NOMBRE.setGeometry(QtCore.QRect(420, 170, 47, 13))
        self.NOMBRE.setObjectName("NOMBRE")
        self.Aceptar = QtWidgets.QPushButton(self.centralwidget)
        self.Aceptar.setGeometry(QtCore.QRect(300, 260, 75, 23))
        self.Aceptar.setObjectName("Aceptar")
        self.Salir = QtWidgets.QPushButton(self.centralwidget)
        self.Salir.setGeometry(QtCore.QRect(410, 260, 75, 23))
        self.Salir.setObjectName("Salir")
        self.DNI = QtWidgets.QLabel(self.centralwidget)
        self.DNI.setGeometry(QtCore.QRect(130, 140, 47, 13))
        self.DNI.setObjectName("DNI")
        self.APEb = QtWidgets.QLineEdit(self.centralwidget)
        self.APEb.setGeometry(QtCore.QRect(200, 170, 191, 20))
        self.APEb.setObjectName("APEb")
        self.DNIb = QtWidgets.QLineEdit(self.centralwidget)
        self.DNIb.setGeometry(QtCore.QRect(200, 140, 191, 20))
        self.DNIb.setObjectName("DNIb")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 100, 721, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.NOMb = QtWidgets.QLineEdit(self.centralwidget)
        self.NOMb.setGeometry(QtCore.QRect(480, 170, 191, 20))
        self.NOMb.setObjectName("NOMb")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(30, 220, 721, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.APELL.setText(_translate("MainWindow", "APELLIDOS:"))
        self.XECL.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.XECL.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.XECL.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">XESTIÓN CLIENTES</span></p></body></html>"))
        self.NOMBRE.setText(_translate("MainWindow", "NOMBRE:"))
        self.Aceptar.setText(_translate("MainWindow", "Aceptar"))
        self.Salir.setText(_translate("MainWindow", "Salir"))
        self.DNI.setText(_translate("MainWindow", "DNI:"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
